import { z } from 'zod';

export const updateProfileSchema = z.object({
    username: z.string().optional(),
    email: z.string().optional(),
    mobileNumber: z.string().optional(),
    birthDate: z.date().optional(),
    gender: z.string().optional(),
    bloodGroup: z.string().optional(),
    adharNumber: z.string().optional(),
    cast: z.string().optional(),
    fatherName: z.string().optional(),
    fatherMobileNumber: z.string().optional(),
    fatherOccupation: z.string().optional(),
    motherName: z.string().optional(),
    motherMobileNumber: z.string().optional(),
    motherOccupation: z.string().optional(),
    localAddress: z.string().optional(),
    city: z.string().optional(),
    district: z.string().optional(),
    state: z.string().optional(),
    pincode: z.string().optional(),
    prnNumber: z.string().optional(),
    tenthMarks: z.string().optional(),
    twelfthDiploma: z.string().optional(),
    twelfthDiplomaPercentage: z.string().optional(),
    admissionBasedOn: z.string().optional(),
    department: z.string().optional(),
    division: z.string().optional(),
    lgName: z.string().optional(),
    sem1SGPA: z.number().optional(),
    sem1CGPA: z.number().optional(),
    sem1Backlog: z.number().optional(),
    sem2SGPA: z.number().optional(),
    sem2CGPA: z.number().optional(),
    sem2Backlog: z.number().optional(),
    sem3SGPA: z.number().optional(),
    sem3CGPA: z.number().optional(),
    sem3Backlog: z.number().optional(),
    sem4SGPA: z.number().optional(),
    sem4CGPA: z.number().optional(),
    sem4Backlog: z.number().optional(),
    sem5SGPA: z.number().optional(),
    sem5CGPA: z.number().optional(),
    sem5Backlog: z.number().optional(),
    sem6SGPA: z.number().optional(),
    sem6CGPA: z.number().optional(),
    sem6Backlog: z.number().optional(),
    passoutYear: z.number().optional(), 
    overallCGPA: z.number().optional(),
    anyLiveKTs: z.number().optional(),
    anyGapDuringEducation: z.string().optional(),
    gapReason: z.string().optional(),
    areaOfInterest: z.string().optional(),
    aboutYou: z.string().optional(),
    projectTitle1: z.string().optional(),
    projectLink1: z.string().optional(),
    projectDescription1: z.string().optional(),
    projectTitle2: z.string().optional(),
    projectLink2: z.string().optional(),
    projectDescription2: z.string().optional(),
    personalPortfolioLink: z.string().optional(),
    githubLink: z.string().optional(),
    linkedinLink: z.string().optional(),
    instagramLink: z.string().optional(),
    twitterLink: z.string().optional(),
    leetcodeLink: z.string().optional(),
    geeksForGeeksLink: z.string().optional(),
    codechefLink: z.string().optional(),
    hackerRankLink: z.string().optional(),
    firstName: z.string().optional(),
    middleName: z.string().optional(),
   
    lastName: z.string().optional(),
    isProfileComplete: z.boolean().optional().default(false), // Correct usage of boolean
    image: z
        .any()
    //     .refine((file) => file?.length == 1, "File is required.")
    //     .refine(
    //         (file) =>
    //             file[0]?.type === "image/png" ||
    //             file[0]?.type === "image/jpeg" ||
    //             file[0]?.type === "image/jpg",
    //         "Must be a png, jpeg or jpg.",
    //     )
    //     .refine((file) => file[0]?.size <= 5000000, `Max file size is 5MB.`),
});
